### ISSUE TITLE
Error when compiling Libium with Cargo install

### ISSUE THREAD

**Issue by SusStew** [gorilla-devs/ferium#416]
### Description

When attempting to install Ferium using Cargo that I installed using the script from rustup.rs, I receive the following error message near the end of the installation steps:

```
Compiling libium v1.26.2
error[E0432]: unresolved import `ferinth::structures::version::Hashes`
 --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libium-1.26.2/src/modpack/modrinth/structs.rs:1:57
  |
1 | use ferinth::structures::{project::ProjectSupportRange, version::Hashes, Int};
  |                                                         ^^^^^^^^^------
  |                                                         |        |
  |                                                         |        help: a similar name exists in the module: `Hash`
  |                                                         no `Hashes` in `structures::version`

error[E0308]: mismatched types
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libium-1.26.2/src/add.rs:36:47
   |
36 |             if Some(StatusCode::NOT_FOUND) == source.status() {
   |                                               ^^^^^^^^^^^^^^^ expected `StatusCode`, found `http::status::StatusCode`
   |
   = note: `http::status::StatusCode` and `StatusCode` have similar names, but are actually distinct types
note: `http::status::StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.1.0/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
note: `StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-0.2.12/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `http` are being used?

error[E0308]: mismatched types
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libium-1.26.2/src/add.rs:50:47
   |
50 |             if Some(StatusCode::NOT_FOUND) == source.status() {
   |                                               ^^^^^^^^^^^^^^^ expected `StatusCode`, found `http::status::StatusCode`
   |
   = note: `http::status::StatusCode` and `StatusCode` have similar names, but are actually distinct types
note: `http::status::StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.1.0/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
note: `StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-0.2.12/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `http` are being used?

error[E0308]: mismatched types
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libium-1.26.2/src/modpack/add.rs:26:47
   |
26 |             if Some(StatusCode::NOT_FOUND) == source.status() {
   |                                               ^^^^^^^^^^^^^^^ expected `StatusCode`, found `http::status::StatusCode`
   |
   = note: `http::status::StatusCode` and `StatusCode` have similar names, but are actually distinct types
note: `http::status::StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.1.0/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
note: `StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-0.2.12/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `http` are being used?

error[E0308]: mismatched types
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libium-1.26.2/src/modpack/add.rs:40:47
   |
40 |             if Some(StatusCode::NOT_FOUND) == source.status() {
   |                                               ^^^^^^^^^^^^^^^ expected `StatusCode`, found `http::status::StatusCode`
   |
   = note: `http::status::StatusCode` and `StatusCode` have similar names, but are actually distinct types
note: `http::status::StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.1.0/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
note: `StatusCode` is defined in crate `http`
  --> /home/azureuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-0.2.12/src/status.rs:45:1
   |
45 | pub struct StatusCode(NonZeroU16);
   | ^^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `http` are being used?

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `libium` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ferium v4.5.2`, intermediate artifacts can be found at `/tmp/cargo-install1iboZk`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

I previously had Ferium installed using Pacstall, but since its version is outdated, I decided to install it using Cargo instead.

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
In an attempt to 'fix' things it seems I've made them even worse:
```
error: could not compile `ferium` (bin "ferium") due to 17 previous errors
```
Anyways I'll release a new version probably tomorrow to fix things.

**Comment by theRookieCoder** [comment]
Fixed in f17a60afd18ce2e2a95531cef676de6e9c2fa3df

**Comment by emalcxe** [comment]
Error may have been reintroduced, as of today `cargo install ferium@4.7.0` still fails to compile.

`error: could not compile `ferium` (bin "ferium") due to 19 previous errors`

**Comment by theRookieCoder** [comment]
You will need to use the `--locked` flag when compiling the older version, since by default it will automatically update libium and it has breaking changes.
